/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.coursework.gherkin.gherkin.And_Statement#getDesc <em>Desc</em>}</li>
 * </ul>
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getAnd_Statement()
 * @model
 * @generated
 */
public interface And_Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Desc</em>' containment reference.
   * @see #setDesc(Description)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getAnd_Statement_Desc()
   * @model containment="true"
   * @generated
   */
  Description getDesc();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.And_Statement#getDesc <em>Desc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Desc</em>' containment reference.
   * @see #getDesc()
   * @generated
   */
  void setDesc(Description value);

} // And_Statement
