/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Background</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.coursework.gherkin.gherkin.Background#getTitle <em>Title</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Background#getBackground_Steps <em>Background Steps</em>}</li>
 * </ul>
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getBackground()
 * @model
 * @generated
 */
public interface Background extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getBackground_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.Background#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Background Steps</b></em>' containment reference list.
   * The list contents are of type {@link mde.coursework.gherkin.gherkin.Steps}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Background Steps</em>' containment reference list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getBackground_Background_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Steps> getBackground_Steps();

} // Background
