/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chain Steps</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.coursework.gherkin.gherkin.Chain_Steps#getChain <em>Chain</em>}</li>
 * </ul>
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getChain_Steps()
 * @model
 * @generated
 */
public interface Chain_Steps extends EObject
{
  /**
   * Returns the value of the '<em><b>Chain</b></em>' containment reference list.
   * The list contents are of type {@link mde.coursework.gherkin.gherkin.Steps}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chain</em>' containment reference list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getChain_Steps_Chain()
   * @model containment="true"
   * @generated
   */
  EList<Steps> getChain();

} // Chain_Steps
