/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getFeature_background <em>Feature background</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getScenarios <em>Scenarios</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getScenario_steps <em>Scenario steps</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getSteps <em>Steps</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getExample <em>Example</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getBackground <em>Background</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getExamples <em>Examples</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getExample_steps <em>Example steps</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.Description#getDesc <em>Desc</em>}</li>
 * </ul>
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription()
 * @model
 * @generated
 */
public interface Description extends Feature, Normal_Scenario, Scenario_Outline, Rule, Example
{
  /**
   * Returns the value of the '<em><b>Feature background</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature background</em>' containment reference.
   * @see #setFeature_background(Background)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Feature_background()
   * @model containment="true"
   * @generated
   */
  Background getFeature_background();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.Description#getFeature_background <em>Feature background</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature background</em>' containment reference.
   * @see #getFeature_background()
   * @generated
   */
  void setFeature_background(Background value);

  /**
   * Returns the value of the '<em><b>Scenarios</b></em>' containment reference list.
   * The list contents are of type {@link mde.coursework.gherkin.gherkin.Scenario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenarios</em>' containment reference list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Scenarios()
   * @model containment="true"
   * @generated
   */
  EList<Scenario> getScenarios();

  /**
   * Returns the value of the '<em><b>Scenario steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario steps</em>' containment reference.
   * @see #setScenario_steps(Chain_Steps)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Scenario_steps()
   * @model containment="true"
   * @generated
   */
  Chain_Steps getScenario_steps();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.Description#getScenario_steps <em>Scenario steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scenario steps</em>' containment reference.
   * @see #getScenario_steps()
   * @generated
   */
  void setScenario_steps(Chain_Steps value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link mde.coursework.gherkin.gherkin.Steps}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Steps> getSteps();

  /**
   * Returns the value of the '<em><b>Example</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Example</em>' containment reference.
   * @see #setExample(Examples)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Example()
   * @model containment="true"
   * @generated
   */
  Examples getExample();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.Description#getExample <em>Example</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Example</em>' containment reference.
   * @see #getExample()
   * @generated
   */
  void setExample(Examples value);

  /**
   * Returns the value of the '<em><b>Background</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Background</em>' containment reference.
   * @see #setBackground(Background)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Background()
   * @model containment="true"
   * @generated
   */
  Background getBackground();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.Description#getBackground <em>Background</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Background</em>' containment reference.
   * @see #getBackground()
   * @generated
   */
  void setBackground(Background value);

  /**
   * Returns the value of the '<em><b>Examples</b></em>' containment reference list.
   * The list contents are of type {@link mde.coursework.gherkin.gherkin.Example}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Examples</em>' containment reference list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Examples()
   * @model containment="true"
   * @generated
   */
  EList<Example> getExamples();

  /**
   * Returns the value of the '<em><b>Example steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Example steps</em>' containment reference.
   * @see #setExample_steps(Chain_Steps)
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Example_steps()
   * @model containment="true"
   * @generated
   */
  Chain_Steps getExample_steps();

  /**
   * Sets the value of the '{@link mde.coursework.gherkin.gherkin.Description#getExample_steps <em>Example steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Example steps</em>' containment reference.
   * @see #getExample_steps()
   * @generated
   */
  void setExample_steps(Chain_Steps value);

  /**
   * Returns the value of the '<em><b>Desc</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Desc</em>' attribute list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getDescription_Desc()
   * @model unique="false"
   * @generated
   */
  EList<String> getDesc();

} // Description
