/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Example</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getExample()
 * @model
 * @generated
 */
public interface Example extends EObject
{
} // Example
