/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mde.coursework.gherkin.gherkin.GherkinFactory
 * @model kind="package"
 * @generated
 */
public interface GherkinPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gherkin";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.coursework.mde/gherkin/Gherkin";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gherkin";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GherkinPackage eINSTANCE = mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl.init();

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Gherkin_LanguageImpl <em>Gherkin Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Gherkin_LanguageImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getGherkin_Language()
   * @generated
   */
  int GHERKIN_LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHERKIN_LANGUAGE__FEATURES = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHERKIN_LANGUAGE__RULES = 1;

  /**
   * The number of structural features of the '<em>Gherkin Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHERKIN_LANGUAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.FeatureImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.BackgroundImpl <em>Background</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.BackgroundImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getBackground()
   * @generated
   */
  int BACKGROUND = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__TITLE = 0;

  /**
   * The feature id for the '<em><b>Background Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND__BACKGROUND_STEPS = 1;

  /**
   * The number of structural features of the '<em>Background</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKGROUND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.ScenarioImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 3;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Normal_ScenarioImpl <em>Normal Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Normal_ScenarioImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getNormal_Scenario()
   * @generated
   */
  int NORMAL_SCENARIO = 4;

  /**
   * The number of structural features of the '<em>Normal Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_SCENARIO_FEATURE_COUNT = SCENARIO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Scenario_OutlineImpl <em>Scenario Outline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Scenario_OutlineImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getScenario_Outline()
   * @generated
   */
  int SCENARIO_OUTLINE = 5;

  /**
   * The number of structural features of the '<em>Scenario Outline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_OUTLINE_FEATURE_COUNT = SCENARIO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.ExamplesImpl <em>Examples</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.ExamplesImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getExamples()
   * @generated
   */
  int EXAMPLES = 6;

  /**
   * The feature id for the '<em><b>Rows</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES__ROWS = 0;

  /**
   * The number of structural features of the '<em>Examples</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.RuleImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getRule()
   * @generated
   */
  int RULE = 7;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.ExampleImpl <em>Example</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.ExampleImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getExample()
   * @generated
   */
  int EXAMPLE = 8;

  /**
   * The number of structural features of the '<em>Example</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXAMPLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Chain_StepsImpl <em>Chain Steps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Chain_StepsImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getChain_Steps()
   * @generated
   */
  int CHAIN_STEPS = 9;

  /**
   * The feature id for the '<em><b>Chain</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_STEPS__CHAIN = 0;

  /**
   * The number of structural features of the '<em>Chain Steps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_STEPS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.StepsImpl <em>Steps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.StepsImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getSteps()
   * @generated
   */
  int STEPS = 10;

  /**
   * The feature id for the '<em><b>Given step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__GIVEN_STEP = 0;

  /**
   * The feature id for the '<em><b>When step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__WHEN_STEP = 1;

  /**
   * The feature id for the '<em><b>But step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__BUT_STEP = 2;

  /**
   * The feature id for the '<em><b>Then step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__THEN_STEP = 3;

  /**
   * The feature id for the '<em><b>And step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__AND_STEP = 4;

  /**
   * The feature id for the '<em><b>Star step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__STAR_STEP = 5;

  /**
   * The number of structural features of the '<em>Steps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Given_StatementImpl <em>Given Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Given_StatementImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getGiven_Statement()
   * @generated
   */
  int GIVEN_STATEMENT = 11;

  /**
   * The feature id for the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN_STATEMENT__DESC = 0;

  /**
   * The number of structural features of the '<em>Given Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GIVEN_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.When_StatementImpl <em>When Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.When_StatementImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getWhen_Statement()
   * @generated
   */
  int WHEN_STATEMENT = 12;

  /**
   * The feature id for the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_STATEMENT__DESC = 0;

  /**
   * The number of structural features of the '<em>When Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Then_StatementImpl <em>Then Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Then_StatementImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getThen_Statement()
   * @generated
   */
  int THEN_STATEMENT = 13;

  /**
   * The feature id for the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_STATEMENT__DESC = 0;

  /**
   * The number of structural features of the '<em>Then Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEN_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.But_StatementImpl <em>But Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.But_StatementImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getBut_Statement()
   * @generated
   */
  int BUT_STATEMENT = 14;

  /**
   * The feature id for the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUT_STATEMENT__DESC = 0;

  /**
   * The number of structural features of the '<em>But Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUT_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.And_StatementImpl <em>And Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.And_StatementImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getAnd_Statement()
   * @generated
   */
  int AND_STATEMENT = 15;

  /**
   * The feature id for the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_STATEMENT__DESC = 0;

  /**
   * The number of structural features of the '<em>And Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.Star_StatementImpl <em>Star Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.Star_StatementImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getStar_Statement()
   * @generated
   */
  int STAR_STATEMENT = 16;

  /**
   * The feature id for the '<em><b>Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAR_STATEMENT__DESC = 0;

  /**
   * The number of structural features of the '<em>Star Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAR_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.DescriptionImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 17;

  /**
   * The feature id for the '<em><b>Feature background</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__FEATURE_BACKGROUND = FEATURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__SCENARIOS = FEATURE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Scenario steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__SCENARIO_STEPS = FEATURE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__STEPS = FEATURE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Example</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__EXAMPLE = FEATURE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Background</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__BACKGROUND = FEATURE_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Examples</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__EXAMPLES = FEATURE_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Example steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__EXAMPLE_STEPS = FEATURE_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__DESC = FEATURE_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = FEATURE_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link mde.coursework.gherkin.gherkin.impl.SentImpl <em>Sent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mde.coursework.gherkin.gherkin.impl.SentImpl
   * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getSent()
   * @generated
   */
  int SENT = 18;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENT__DESC = 0;

  /**
   * The number of structural features of the '<em>Sent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Gherkin_Language <em>Gherkin Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gherkin Language</em>'.
   * @see mde.coursework.gherkin.gherkin.Gherkin_Language
   * @generated
   */
  EClass getGherkin_Language();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Gherkin_Language#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see mde.coursework.gherkin.gherkin.Gherkin_Language#getFeatures()
   * @see #getGherkin_Language()
   * @generated
   */
  EReference getGherkin_Language_Features();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Gherkin_Language#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see mde.coursework.gherkin.gherkin.Gherkin_Language#getRules()
   * @see #getGherkin_Language()
   * @generated
   */
  EReference getGherkin_Language_Rules();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see mde.coursework.gherkin.gherkin.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Background <em>Background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Background</em>'.
   * @see mde.coursework.gherkin.gherkin.Background
   * @generated
   */
  EClass getBackground();

  /**
   * Returns the meta object for the attribute '{@link mde.coursework.gherkin.gherkin.Background#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see mde.coursework.gherkin.gherkin.Background#getTitle()
   * @see #getBackground()
   * @generated
   */
  EAttribute getBackground_Title();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Background#getBackground_Steps <em>Background Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Background Steps</em>'.
   * @see mde.coursework.gherkin.gherkin.Background#getBackground_Steps()
   * @see #getBackground()
   * @generated
   */
  EReference getBackground_Background_Steps();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see mde.coursework.gherkin.gherkin.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Normal_Scenario <em>Normal Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Scenario</em>'.
   * @see mde.coursework.gherkin.gherkin.Normal_Scenario
   * @generated
   */
  EClass getNormal_Scenario();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Scenario_Outline <em>Scenario Outline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario Outline</em>'.
   * @see mde.coursework.gherkin.gherkin.Scenario_Outline
   * @generated
   */
  EClass getScenario_Outline();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Examples <em>Examples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Examples</em>'.
   * @see mde.coursework.gherkin.gherkin.Examples
   * @generated
   */
  EClass getExamples();

  /**
   * Returns the meta object for the attribute list '{@link mde.coursework.gherkin.gherkin.Examples#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Rows</em>'.
   * @see mde.coursework.gherkin.gherkin.Examples#getRows()
   * @see #getExamples()
   * @generated
   */
  EAttribute getExamples_Rows();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see mde.coursework.gherkin.gherkin.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Example <em>Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Example</em>'.
   * @see mde.coursework.gherkin.gherkin.Example
   * @generated
   */
  EClass getExample();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Chain_Steps <em>Chain Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chain Steps</em>'.
   * @see mde.coursework.gherkin.gherkin.Chain_Steps
   * @generated
   */
  EClass getChain_Steps();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Chain_Steps#getChain <em>Chain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Chain</em>'.
   * @see mde.coursework.gherkin.gherkin.Chain_Steps#getChain()
   * @see #getChain_Steps()
   * @generated
   */
  EReference getChain_Steps_Chain();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Steps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Steps</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps
   * @generated
   */
  EClass getSteps();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Steps#getGiven_step <em>Given step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Given step</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps#getGiven_step()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_Given_step();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Steps#getWhen_step <em>When step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>When step</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps#getWhen_step()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_When_step();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Steps#getBut_step <em>But step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>But step</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps#getBut_step()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_But_step();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Steps#getThen_step <em>Then step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then step</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps#getThen_step()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_Then_step();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Steps#getAnd_step <em>And step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>And step</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps#getAnd_step()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_And_step();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Steps#getStar_step <em>Star step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Star step</em>'.
   * @see mde.coursework.gherkin.gherkin.Steps#getStar_step()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_Star_step();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Given_Statement <em>Given Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Given Statement</em>'.
   * @see mde.coursework.gherkin.gherkin.Given_Statement
   * @generated
   */
  EClass getGiven_Statement();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Given_Statement#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.Given_Statement#getDesc()
   * @see #getGiven_Statement()
   * @generated
   */
  EReference getGiven_Statement_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.When_Statement <em>When Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>When Statement</em>'.
   * @see mde.coursework.gherkin.gherkin.When_Statement
   * @generated
   */
  EClass getWhen_Statement();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.When_Statement#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.When_Statement#getDesc()
   * @see #getWhen_Statement()
   * @generated
   */
  EReference getWhen_Statement_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Then_Statement <em>Then Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Then Statement</em>'.
   * @see mde.coursework.gherkin.gherkin.Then_Statement
   * @generated
   */
  EClass getThen_Statement();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Then_Statement#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.Then_Statement#getDesc()
   * @see #getThen_Statement()
   * @generated
   */
  EReference getThen_Statement_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.But_Statement <em>But Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>But Statement</em>'.
   * @see mde.coursework.gherkin.gherkin.But_Statement
   * @generated
   */
  EClass getBut_Statement();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.But_Statement#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.But_Statement#getDesc()
   * @see #getBut_Statement()
   * @generated
   */
  EReference getBut_Statement_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.And_Statement <em>And Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Statement</em>'.
   * @see mde.coursework.gherkin.gherkin.And_Statement
   * @generated
   */
  EClass getAnd_Statement();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.And_Statement#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.And_Statement#getDesc()
   * @see #getAnd_Statement()
   * @generated
   */
  EReference getAnd_Statement_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Star_Statement <em>Star Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Star Statement</em>'.
   * @see mde.coursework.gherkin.gherkin.Star_Statement
   * @generated
   */
  EClass getStar_Statement();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Star_Statement#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.Star_Statement#getDesc()
   * @see #getStar_Statement()
   * @generated
   */
  EReference getStar_Statement_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see mde.coursework.gherkin.gherkin.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Description#getFeature_background <em>Feature background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Feature background</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getFeature_background()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Feature_background();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Description#getScenarios <em>Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenarios</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getScenarios()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Scenarios();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Description#getScenario_steps <em>Scenario steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scenario steps</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getScenario_steps()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Scenario_steps();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Description#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getSteps()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Steps();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Description#getExample <em>Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Example</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getExample()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Example();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Description#getBackground <em>Background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Background</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getBackground()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Background();

  /**
   * Returns the meta object for the containment reference list '{@link mde.coursework.gherkin.gherkin.Description#getExamples <em>Examples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Examples</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getExamples()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Examples();

  /**
   * Returns the meta object for the containment reference '{@link mde.coursework.gherkin.gherkin.Description#getExample_steps <em>Example steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Example steps</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getExample_steps()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Example_steps();

  /**
   * Returns the meta object for the attribute list '{@link mde.coursework.gherkin.gherkin.Description#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.Description#getDesc()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Desc();

  /**
   * Returns the meta object for class '{@link mde.coursework.gherkin.gherkin.Sent <em>Sent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sent</em>'.
   * @see mde.coursework.gherkin.gherkin.Sent
   * @generated
   */
  EClass getSent();

  /**
   * Returns the meta object for the attribute list '{@link mde.coursework.gherkin.gherkin.Sent#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Desc</em>'.
   * @see mde.coursework.gherkin.gherkin.Sent#getDesc()
   * @see #getSent()
   * @generated
   */
  EAttribute getSent_Desc();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GherkinFactory getGherkinFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Gherkin_LanguageImpl <em>Gherkin Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Gherkin_LanguageImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getGherkin_Language()
     * @generated
     */
    EClass GHERKIN_LANGUAGE = eINSTANCE.getGherkin_Language();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GHERKIN_LANGUAGE__FEATURES = eINSTANCE.getGherkin_Language_Features();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GHERKIN_LANGUAGE__RULES = eINSTANCE.getGherkin_Language_Rules();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.FeatureImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.BackgroundImpl <em>Background</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.BackgroundImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getBackground()
     * @generated
     */
    EClass BACKGROUND = eINSTANCE.getBackground();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKGROUND__TITLE = eINSTANCE.getBackground_Title();

    /**
     * The meta object literal for the '<em><b>Background Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BACKGROUND__BACKGROUND_STEPS = eINSTANCE.getBackground_Background_Steps();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.ScenarioImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Normal_ScenarioImpl <em>Normal Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Normal_ScenarioImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getNormal_Scenario()
     * @generated
     */
    EClass NORMAL_SCENARIO = eINSTANCE.getNormal_Scenario();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Scenario_OutlineImpl <em>Scenario Outline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Scenario_OutlineImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getScenario_Outline()
     * @generated
     */
    EClass SCENARIO_OUTLINE = eINSTANCE.getScenario_Outline();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.ExamplesImpl <em>Examples</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.ExamplesImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getExamples()
     * @generated
     */
    EClass EXAMPLES = eINSTANCE.getExamples();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXAMPLES__ROWS = eINSTANCE.getExamples_Rows();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.RuleImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.ExampleImpl <em>Example</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.ExampleImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getExample()
     * @generated
     */
    EClass EXAMPLE = eINSTANCE.getExample();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Chain_StepsImpl <em>Chain Steps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Chain_StepsImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getChain_Steps()
     * @generated
     */
    EClass CHAIN_STEPS = eINSTANCE.getChain_Steps();

    /**
     * The meta object literal for the '<em><b>Chain</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAIN_STEPS__CHAIN = eINSTANCE.getChain_Steps_Chain();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.StepsImpl <em>Steps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.StepsImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getSteps()
     * @generated
     */
    EClass STEPS = eINSTANCE.getSteps();

    /**
     * The meta object literal for the '<em><b>Given step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__GIVEN_STEP = eINSTANCE.getSteps_Given_step();

    /**
     * The meta object literal for the '<em><b>When step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__WHEN_STEP = eINSTANCE.getSteps_When_step();

    /**
     * The meta object literal for the '<em><b>But step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__BUT_STEP = eINSTANCE.getSteps_But_step();

    /**
     * The meta object literal for the '<em><b>Then step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__THEN_STEP = eINSTANCE.getSteps_Then_step();

    /**
     * The meta object literal for the '<em><b>And step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__AND_STEP = eINSTANCE.getSteps_And_step();

    /**
     * The meta object literal for the '<em><b>Star step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__STAR_STEP = eINSTANCE.getSteps_Star_step();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Given_StatementImpl <em>Given Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Given_StatementImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getGiven_Statement()
     * @generated
     */
    EClass GIVEN_STATEMENT = eINSTANCE.getGiven_Statement();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GIVEN_STATEMENT__DESC = eINSTANCE.getGiven_Statement_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.When_StatementImpl <em>When Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.When_StatementImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getWhen_Statement()
     * @generated
     */
    EClass WHEN_STATEMENT = eINSTANCE.getWhen_Statement();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHEN_STATEMENT__DESC = eINSTANCE.getWhen_Statement_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Then_StatementImpl <em>Then Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Then_StatementImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getThen_Statement()
     * @generated
     */
    EClass THEN_STATEMENT = eINSTANCE.getThen_Statement();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference THEN_STATEMENT__DESC = eINSTANCE.getThen_Statement_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.But_StatementImpl <em>But Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.But_StatementImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getBut_Statement()
     * @generated
     */
    EClass BUT_STATEMENT = eINSTANCE.getBut_Statement();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUT_STATEMENT__DESC = eINSTANCE.getBut_Statement_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.And_StatementImpl <em>And Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.And_StatementImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getAnd_Statement()
     * @generated
     */
    EClass AND_STATEMENT = eINSTANCE.getAnd_Statement();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_STATEMENT__DESC = eINSTANCE.getAnd_Statement_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.Star_StatementImpl <em>Star Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.Star_StatementImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getStar_Statement()
     * @generated
     */
    EClass STAR_STATEMENT = eINSTANCE.getStar_Statement();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STAR_STATEMENT__DESC = eINSTANCE.getStar_Statement_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.DescriptionImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Feature background</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__FEATURE_BACKGROUND = eINSTANCE.getDescription_Feature_background();

    /**
     * The meta object literal for the '<em><b>Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__SCENARIOS = eINSTANCE.getDescription_Scenarios();

    /**
     * The meta object literal for the '<em><b>Scenario steps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__SCENARIO_STEPS = eINSTANCE.getDescription_Scenario_steps();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__STEPS = eINSTANCE.getDescription_Steps();

    /**
     * The meta object literal for the '<em><b>Example</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__EXAMPLE = eINSTANCE.getDescription_Example();

    /**
     * The meta object literal for the '<em><b>Background</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__BACKGROUND = eINSTANCE.getDescription_Background();

    /**
     * The meta object literal for the '<em><b>Examples</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__EXAMPLES = eINSTANCE.getDescription_Examples();

    /**
     * The meta object literal for the '<em><b>Example steps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__EXAMPLE_STEPS = eINSTANCE.getDescription_Example_steps();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__DESC = eINSTANCE.getDescription_Desc();

    /**
     * The meta object literal for the '{@link mde.coursework.gherkin.gherkin.impl.SentImpl <em>Sent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mde.coursework.gherkin.gherkin.impl.SentImpl
     * @see mde.coursework.gherkin.gherkin.impl.GherkinPackageImpl#getSent()
     * @generated
     */
    EClass SENT = eINSTANCE.getSent();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENT__DESC = eINSTANCE.getSent_Desc();

  }

} //GherkinPackage
