/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getNormal_Scenario()
 * @model
 * @generated
 */
public interface Normal_Scenario extends Scenario
{
} // Normal_Scenario
