/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Outline</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getScenario_Outline()
 * @model
 * @generated
 */
public interface Scenario_Outline extends Scenario
{
} // Scenario_Outline
