/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.coursework.gherkin.gherkin.Sent#getDesc <em>Desc</em>}</li>
 * </ul>
 *
 * @see mde.coursework.gherkin.gherkin.GherkinPackage#getSent()
 * @model
 * @generated
 */
public interface Sent extends EObject
{
  /**
   * Returns the value of the '<em><b>Desc</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Desc</em>' attribute list.
   * @see mde.coursework.gherkin.gherkin.GherkinPackage#getSent_Desc()
   * @model unique="false"
   * @generated
   */
  EList<String> getDesc();

} // Sent
