/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GherkinUiModule extends AbstractGherkinUiModule {

	public GherkinUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
