/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GherkinRuntimeModule extends AbstractGherkinRuntimeModule {
}
