/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GherkinStandaloneSetup extends GherkinStandaloneSetupGenerated {

	public static void doSetup() {
		new GherkinStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
