/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGherkinScopeProvider extends DelegatingScopeProvider {
}
