/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GherkinAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mde/coursework/gherkin/parser/antlr/internal/InternalGherkinParser.tokens");
	}
}
