/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.ui;

import com.google.inject.Injector;
import mde.coursework.gherkin.ui.internal.GherkinActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GherkinExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GherkinActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GherkinActivator activator = GherkinActivator.getInstance();
		return activator != null ? activator.getInjector(GherkinActivator.MDE_COURSEWORK_GHERKIN_GHERKIN) : null;
	}

}
