/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGherkinValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mde.coursework.gherkin.gherkin.GherkinPackage.eINSTANCE);
		return result;
	}
}
