/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin.impl;

import java.util.Collection;

import mde.coursework.gherkin.gherkin.Background;
import mde.coursework.gherkin.gherkin.Chain_Steps;
import mde.coursework.gherkin.gherkin.Description;
import mde.coursework.gherkin.gherkin.Example;
import mde.coursework.gherkin.gherkin.Examples;
import mde.coursework.gherkin.gherkin.GherkinPackage;
import mde.coursework.gherkin.gherkin.Scenario;
import mde.coursework.gherkin.gherkin.Steps;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Description</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getFeature_background <em>Feature background</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getScenarios <em>Scenarios</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getScenario_steps <em>Scenario steps</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getSteps <em>Steps</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getExample <em>Example</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getBackground <em>Background</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getExamples <em>Examples</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getExample_steps <em>Example steps</em>}</li>
 *   <li>{@link mde.coursework.gherkin.gherkin.impl.DescriptionImpl#getDesc <em>Desc</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DescriptionImpl extends FeatureImpl implements Description
{
  /**
   * The cached value of the '{@link #getFeature_background() <em>Feature background</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeature_background()
   * @generated
   * @ordered
   */
  protected Background feature_background;

  /**
   * The cached value of the '{@link #getScenarios() <em>Scenarios</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getScenarios()
   * @generated
   * @ordered
   */
  protected EList<Scenario> scenarios;

  /**
   * The cached value of the '{@link #getScenario_steps() <em>Scenario steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getScenario_steps()
   * @generated
   * @ordered
   */
  protected Chain_Steps scenario_steps;

  /**
   * The cached value of the '{@link #getSteps() <em>Steps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected EList<Steps> steps;

  /**
   * The cached value of the '{@link #getExample() <em>Example</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExample()
   * @generated
   * @ordered
   */
  protected Examples example;

  /**
   * The cached value of the '{@link #getBackground() <em>Background</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBackground()
   * @generated
   * @ordered
   */
  protected Background background;

  /**
   * The cached value of the '{@link #getExamples() <em>Examples</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExamples()
   * @generated
   * @ordered
   */
  protected EList<Example> examples;

  /**
   * The cached value of the '{@link #getExample_steps() <em>Example steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExample_steps()
   * @generated
   * @ordered
   */
  protected Chain_Steps example_steps;

  /**
   * The cached value of the '{@link #getDesc() <em>Desc</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesc()
   * @generated
   * @ordered
   */
  protected EList<String> desc;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GherkinPackage.Literals.DESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Background getFeature_background()
  {
    return feature_background;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFeature_background(Background newFeature_background, NotificationChain msgs)
  {
    Background oldFeature_background = feature_background;
    feature_background = newFeature_background;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND, oldFeature_background, newFeature_background);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFeature_background(Background newFeature_background)
  {
    if (newFeature_background != feature_background)
    {
      NotificationChain msgs = null;
      if (feature_background != null)
        msgs = ((InternalEObject)feature_background).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND, null, msgs);
      if (newFeature_background != null)
        msgs = ((InternalEObject)newFeature_background).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND, null, msgs);
      msgs = basicSetFeature_background(newFeature_background, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND, newFeature_background, newFeature_background));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Scenario> getScenarios()
  {
    if (scenarios == null)
    {
      scenarios = new EObjectContainmentEList<Scenario>(Scenario.class, this, GherkinPackage.DESCRIPTION__SCENARIOS);
    }
    return scenarios;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Chain_Steps getScenario_steps()
  {
    return scenario_steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetScenario_steps(Chain_Steps newScenario_steps, NotificationChain msgs)
  {
    Chain_Steps oldScenario_steps = scenario_steps;
    scenario_steps = newScenario_steps;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__SCENARIO_STEPS, oldScenario_steps, newScenario_steps);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setScenario_steps(Chain_Steps newScenario_steps)
  {
    if (newScenario_steps != scenario_steps)
    {
      NotificationChain msgs = null;
      if (scenario_steps != null)
        msgs = ((InternalEObject)scenario_steps).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__SCENARIO_STEPS, null, msgs);
      if (newScenario_steps != null)
        msgs = ((InternalEObject)newScenario_steps).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__SCENARIO_STEPS, null, msgs);
      msgs = basicSetScenario_steps(newScenario_steps, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__SCENARIO_STEPS, newScenario_steps, newScenario_steps));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Steps> getSteps()
  {
    if (steps == null)
    {
      steps = new EObjectContainmentEList<Steps>(Steps.class, this, GherkinPackage.DESCRIPTION__STEPS);
    }
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Examples getExample()
  {
    return example;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExample(Examples newExample, NotificationChain msgs)
  {
    Examples oldExample = example;
    example = newExample;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__EXAMPLE, oldExample, newExample);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExample(Examples newExample)
  {
    if (newExample != example)
    {
      NotificationChain msgs = null;
      if (example != null)
        msgs = ((InternalEObject)example).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__EXAMPLE, null, msgs);
      if (newExample != null)
        msgs = ((InternalEObject)newExample).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__EXAMPLE, null, msgs);
      msgs = basicSetExample(newExample, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__EXAMPLE, newExample, newExample));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Background getBackground()
  {
    return background;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBackground(Background newBackground, NotificationChain msgs)
  {
    Background oldBackground = background;
    background = newBackground;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__BACKGROUND, oldBackground, newBackground);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBackground(Background newBackground)
  {
    if (newBackground != background)
    {
      NotificationChain msgs = null;
      if (background != null)
        msgs = ((InternalEObject)background).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__BACKGROUND, null, msgs);
      if (newBackground != null)
        msgs = ((InternalEObject)newBackground).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__BACKGROUND, null, msgs);
      msgs = basicSetBackground(newBackground, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__BACKGROUND, newBackground, newBackground));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Example> getExamples()
  {
    if (examples == null)
    {
      examples = new EObjectContainmentEList<Example>(Example.class, this, GherkinPackage.DESCRIPTION__EXAMPLES);
    }
    return examples;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Chain_Steps getExample_steps()
  {
    return example_steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExample_steps(Chain_Steps newExample_steps, NotificationChain msgs)
  {
    Chain_Steps oldExample_steps = example_steps;
    example_steps = newExample_steps;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__EXAMPLE_STEPS, oldExample_steps, newExample_steps);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExample_steps(Chain_Steps newExample_steps)
  {
    if (newExample_steps != example_steps)
    {
      NotificationChain msgs = null;
      if (example_steps != null)
        msgs = ((InternalEObject)example_steps).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__EXAMPLE_STEPS, null, msgs);
      if (newExample_steps != null)
        msgs = ((InternalEObject)newExample_steps).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GherkinPackage.DESCRIPTION__EXAMPLE_STEPS, null, msgs);
      msgs = basicSetExample_steps(newExample_steps, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GherkinPackage.DESCRIPTION__EXAMPLE_STEPS, newExample_steps, newExample_steps));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getDesc()
  {
    if (desc == null)
    {
      desc = new EDataTypeEList<String>(String.class, this, GherkinPackage.DESCRIPTION__DESC);
    }
    return desc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND:
        return basicSetFeature_background(null, msgs);
      case GherkinPackage.DESCRIPTION__SCENARIOS:
        return ((InternalEList<?>)getScenarios()).basicRemove(otherEnd, msgs);
      case GherkinPackage.DESCRIPTION__SCENARIO_STEPS:
        return basicSetScenario_steps(null, msgs);
      case GherkinPackage.DESCRIPTION__STEPS:
        return ((InternalEList<?>)getSteps()).basicRemove(otherEnd, msgs);
      case GherkinPackage.DESCRIPTION__EXAMPLE:
        return basicSetExample(null, msgs);
      case GherkinPackage.DESCRIPTION__BACKGROUND:
        return basicSetBackground(null, msgs);
      case GherkinPackage.DESCRIPTION__EXAMPLES:
        return ((InternalEList<?>)getExamples()).basicRemove(otherEnd, msgs);
      case GherkinPackage.DESCRIPTION__EXAMPLE_STEPS:
        return basicSetExample_steps(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND:
        return getFeature_background();
      case GherkinPackage.DESCRIPTION__SCENARIOS:
        return getScenarios();
      case GherkinPackage.DESCRIPTION__SCENARIO_STEPS:
        return getScenario_steps();
      case GherkinPackage.DESCRIPTION__STEPS:
        return getSteps();
      case GherkinPackage.DESCRIPTION__EXAMPLE:
        return getExample();
      case GherkinPackage.DESCRIPTION__BACKGROUND:
        return getBackground();
      case GherkinPackage.DESCRIPTION__EXAMPLES:
        return getExamples();
      case GherkinPackage.DESCRIPTION__EXAMPLE_STEPS:
        return getExample_steps();
      case GherkinPackage.DESCRIPTION__DESC:
        return getDesc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND:
        setFeature_background((Background)newValue);
        return;
      case GherkinPackage.DESCRIPTION__SCENARIOS:
        getScenarios().clear();
        getScenarios().addAll((Collection<? extends Scenario>)newValue);
        return;
      case GherkinPackage.DESCRIPTION__SCENARIO_STEPS:
        setScenario_steps((Chain_Steps)newValue);
        return;
      case GherkinPackage.DESCRIPTION__STEPS:
        getSteps().clear();
        getSteps().addAll((Collection<? extends Steps>)newValue);
        return;
      case GherkinPackage.DESCRIPTION__EXAMPLE:
        setExample((Examples)newValue);
        return;
      case GherkinPackage.DESCRIPTION__BACKGROUND:
        setBackground((Background)newValue);
        return;
      case GherkinPackage.DESCRIPTION__EXAMPLES:
        getExamples().clear();
        getExamples().addAll((Collection<? extends Example>)newValue);
        return;
      case GherkinPackage.DESCRIPTION__EXAMPLE_STEPS:
        setExample_steps((Chain_Steps)newValue);
        return;
      case GherkinPackage.DESCRIPTION__DESC:
        getDesc().clear();
        getDesc().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND:
        setFeature_background((Background)null);
        return;
      case GherkinPackage.DESCRIPTION__SCENARIOS:
        getScenarios().clear();
        return;
      case GherkinPackage.DESCRIPTION__SCENARIO_STEPS:
        setScenario_steps((Chain_Steps)null);
        return;
      case GherkinPackage.DESCRIPTION__STEPS:
        getSteps().clear();
        return;
      case GherkinPackage.DESCRIPTION__EXAMPLE:
        setExample((Examples)null);
        return;
      case GherkinPackage.DESCRIPTION__BACKGROUND:
        setBackground((Background)null);
        return;
      case GherkinPackage.DESCRIPTION__EXAMPLES:
        getExamples().clear();
        return;
      case GherkinPackage.DESCRIPTION__EXAMPLE_STEPS:
        setExample_steps((Chain_Steps)null);
        return;
      case GherkinPackage.DESCRIPTION__DESC:
        getDesc().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GherkinPackage.DESCRIPTION__FEATURE_BACKGROUND:
        return feature_background != null;
      case GherkinPackage.DESCRIPTION__SCENARIOS:
        return scenarios != null && !scenarios.isEmpty();
      case GherkinPackage.DESCRIPTION__SCENARIO_STEPS:
        return scenario_steps != null;
      case GherkinPackage.DESCRIPTION__STEPS:
        return steps != null && !steps.isEmpty();
      case GherkinPackage.DESCRIPTION__EXAMPLE:
        return example != null;
      case GherkinPackage.DESCRIPTION__BACKGROUND:
        return background != null;
      case GherkinPackage.DESCRIPTION__EXAMPLES:
        return examples != null && !examples.isEmpty();
      case GherkinPackage.DESCRIPTION__EXAMPLE_STEPS:
        return example_steps != null;
      case GherkinPackage.DESCRIPTION__DESC:
        return desc != null && !desc.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (desc: ");
    result.append(desc);
    result.append(')');
    return result.toString();
  }

} //DescriptionImpl
