/**
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.gherkin.impl;

import mde.coursework.gherkin.gherkin.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GherkinFactoryImpl extends EFactoryImpl implements GherkinFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GherkinFactory init()
  {
    try
    {
      GherkinFactory theGherkinFactory = (GherkinFactory)EPackage.Registry.INSTANCE.getEFactory(GherkinPackage.eNS_URI);
      if (theGherkinFactory != null)
      {
        return theGherkinFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GherkinFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GherkinFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GherkinPackage.GHERKIN_LANGUAGE: return createGherkin_Language();
      case GherkinPackage.FEATURE: return createFeature();
      case GherkinPackage.BACKGROUND: return createBackground();
      case GherkinPackage.SCENARIO: return createScenario();
      case GherkinPackage.NORMAL_SCENARIO: return createNormal_Scenario();
      case GherkinPackage.SCENARIO_OUTLINE: return createScenario_Outline();
      case GherkinPackage.EXAMPLES: return createExamples();
      case GherkinPackage.RULE: return createRule();
      case GherkinPackage.EXAMPLE: return createExample();
      case GherkinPackage.CHAIN_STEPS: return createChain_Steps();
      case GherkinPackage.STEPS: return createSteps();
      case GherkinPackage.GIVEN_STATEMENT: return createGiven_Statement();
      case GherkinPackage.WHEN_STATEMENT: return createWhen_Statement();
      case GherkinPackage.THEN_STATEMENT: return createThen_Statement();
      case GherkinPackage.BUT_STATEMENT: return createBut_Statement();
      case GherkinPackage.AND_STATEMENT: return createAnd_Statement();
      case GherkinPackage.STAR_STATEMENT: return createStar_Statement();
      case GherkinPackage.DESCRIPTION: return createDescription();
      case GherkinPackage.SENT: return createSent();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Gherkin_Language createGherkin_Language()
  {
    Gherkin_LanguageImpl gherkin_Language = new Gherkin_LanguageImpl();
    return gherkin_Language;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Feature createFeature()
  {
    FeatureImpl feature = new FeatureImpl();
    return feature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Background createBackground()
  {
    BackgroundImpl background = new BackgroundImpl();
    return background;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Scenario createScenario()
  {
    ScenarioImpl scenario = new ScenarioImpl();
    return scenario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Normal_Scenario createNormal_Scenario()
  {
    Normal_ScenarioImpl normal_Scenario = new Normal_ScenarioImpl();
    return normal_Scenario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Scenario_Outline createScenario_Outline()
  {
    Scenario_OutlineImpl scenario_Outline = new Scenario_OutlineImpl();
    return scenario_Outline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Examples createExamples()
  {
    ExamplesImpl examples = new ExamplesImpl();
    return examples;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rule createRule()
  {
    RuleImpl rule = new RuleImpl();
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Example createExample()
  {
    ExampleImpl example = new ExampleImpl();
    return example;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Chain_Steps createChain_Steps()
  {
    Chain_StepsImpl chain_Steps = new Chain_StepsImpl();
    return chain_Steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Steps createSteps()
  {
    StepsImpl steps = new StepsImpl();
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Given_Statement createGiven_Statement()
  {
    Given_StatementImpl given_Statement = new Given_StatementImpl();
    return given_Statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public When_Statement createWhen_Statement()
  {
    When_StatementImpl when_Statement = new When_StatementImpl();
    return when_Statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Then_Statement createThen_Statement()
  {
    Then_StatementImpl then_Statement = new Then_StatementImpl();
    return then_Statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public But_Statement createBut_Statement()
  {
    But_StatementImpl but_Statement = new But_StatementImpl();
    return but_Statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public And_Statement createAnd_Statement()
  {
    And_StatementImpl and_Statement = new And_StatementImpl();
    return and_Statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Star_Statement createStar_Statement()
  {
    Star_StatementImpl star_Statement = new Star_StatementImpl();
    return star_Statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Description createDescription()
  {
    DescriptionImpl description = new DescriptionImpl();
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sent createSent()
  {
    SentImpl sent = new SentImpl();
    return sent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GherkinPackage getGherkinPackage()
  {
    return (GherkinPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GherkinPackage getPackage()
  {
    return GherkinPackage.eINSTANCE;
  }

} //GherkinFactoryImpl
