/*
 * generated by Xtext 2.24.0
 */
package mde.coursework.gherkin.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mde.coursework.gherkin.GherkinRuntimeModule;
import mde.coursework.gherkin.GherkinStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GherkinIdeSetup extends GherkinStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GherkinRuntimeModule(), new GherkinIdeModule()));
	}
	
}
